module.exports = {
  html: {
    Array: [
      'html/001',
      'html/002',
      'html/003',
      'html/004',
      'html/005',
      'html/006',
      'html/007',
      'html/008',
      'html/009',
      'html/010',
      'html/011',
      'html/012',
      'html/013',
      'html/014',
      'html/015',
      'html/016',
      'html/017',
      'html/018',
      'html/019',
      'html/020',
      'html/021',
      'html/022',
      'html/023',
      'html/024',
      'html/025',
      'html/026',
      'html/027',
      'html/028',
      'html/029',
      'html/030',
      'html/031',
      'html/032',
      'html/033',
      'html/034',
      'html/035',
      'html/036',
      'html/037',
    ],
  },
  leetcode: {
    leetcodeSolutions: [
      'leetcode/0001',
      'leetcode/0002',
      'leetcode/0003',
      'leetcode/0004',
      'leetcode/0005',
      'leetcode/0006',
      'leetcode/0007',
      'leetcode/0008',
      'leetcode/0009',
      'leetcode/0010',
    ],
  },
  hooks: [
    'hooks/useWindowSize',
    'hooks/useHover',
    'hooks/useLockBodyScroll',
    'hooks/useEventListener',
    'hooks/useTheme',
    'hooks/useScript',
    'hooks/usePrevious',
  ],
  someSidebar: {
    Array: [
      'polyfill/concat',
      'polyfill/every',
      'polyfill/fill',
      'polyfill/filter',
      'polyfill/find',
      'polyfill/findIndex',
      'polyfill/forEach',
      'polyfill/includes',
      'polyfill/indexOf',
      'polyfill/isArray',
      'polyfill/join',
      'polyfill/lastIndexOf',
      'polyfill/map',
      'polyfill/of',
      'polyfill/reduce',
      'polyfill/reverse',
      'polyfill/slice',
      'polyfill/some',
      'polyfill/toLocalString',
    ],
    Function: ['polyfill/apply', 'polyfill/bind', 'polyfill/call'],
    Object: [
      'polyfill/assign',
      'polyfill/create',
      'polyfill/defineProperties',
      'polyfill/entries',
      'polyfill/is',
      'polyfill/keys',
    ],
  },
};
