module.exports = {
  html: { Array: ['html/concat', 'html/every'] },
  someSidebar: {
    Array: [
      'polyfill/concat',
      'polyfill/every',
      'polyfill/fill',
      'polyfill/filter',
      'polyfill/find',
      'polyfill/findIndex',
      'polyfill/forEach',
      'polyfill/includes',
      'polyfill/indexOf',
      'polyfill/isArray',
      'polyfill/join',
      'polyfill/lastIndexOf',
      'polyfill/map',
      'polyfill/of',
      'polyfill/reduce',
      'polyfill/reverse',
      'polyfill/slice',
      'polyfill/some',
      'polyfill/toLocalString',
    ],
    Function: ['polyfill/apply', 'polyfill/bind', 'polyfill/call'],
    Object: [
      'polyfill/assign',
      'polyfill/create',
      'polyfill/defineProperties',
      'polyfill/entries',
      'polyfill/is',
      'polyfill/keys',
    ],
    Foo: ['foo/concat'],
  },
};
