module.exports = {
  someSidebar: {
    Array: [
      'concat',
      'every',
      'fill',
      'filter',
      'find',
      'findIndex',
      'forEach',
      'includes',
      'indexOf',
      'isArray',
      'join',
      'lastIndexOf',
      'map',
      'of',
      'reduce',
      'reverse',
      'slice',
      'some',
      'toLocalString',
    ],
    Function: ['apply', 'bind', 'call'],
    Object: ['assign', 'create', 'defineProperties', 'entries', 'is', 'keys'],
  },
};
